#ifndef ERRORS_H
# define ERRORS_H

# define ERROR_HEADER   "ERROR\n"
# define ERROR_ERRNO    -1

typedef enum e_error
{
	ERROR_PATH_EMPTY = 0,
	ERROR_PATH_PARAM_EMPTY,
	ERROR_SCREENSHOT_PARAM_WRONG,
	ERROR_NUM_ARGS_WRONG,
	ERROR_SCENE_EXT_WRONG,
	ERROR_SYNTAX_RESOLUTION,
	ERROR_SYNTAX_AMBIENCE,
	ERROR_SYNTAX_CAMERA,
	ERROR_SYNTAX_LIGHT,
	ERROR_SYNTAX_SPHERE,
	ERROR_SYNTAX_CYLINDER,
	ERROR_SYNTAX_PLANE,
	ERROR_SYNTAX_TRIANGLE,
	ERROR_SYNTAX_SQUARE
}   t_error;

void    ft_perror(int code);
void    ft_pexit(int code, int status);

#endif